---
apiVersion: v1
kind: Pod
metadata:
  name: validator
  labels:
    app: validator
spec:
  containers:
  - name: validator
    image: solanalabs/solana:v1.9.12
    ports:
    - containerPort: 8899
    - containerPort: 8900
    - containerPort: 9900
---
apiVersion: v1
kind: Service
metadata:
  name: validator
spec:
  type: NodePort
  selector:
    app: validator
  ports:
  - protocol: TCP
    port: 8899
    nodePort: 31899
    name: rpc-http
  - protocol: TCP
    port: 8900
    nodePort: 31890
    name: rpc-websocket
  - protocol: TCP
    port: 9900
    nodePort: 31990
    name: faucet